### ISSUE TITLE
Come out a non-hacky way for students to download input files

### ISSUE THREAD

**Issue by TimeString** [nesl/AutoGrader#105]
As I can recall, when a user clicks the download button in the assignment table in the assignment page, the user only gets the first file if there are multiple input files, which is not correct and we didn't have a chance to resolve it in time before we released the last assignment. The goal of this issue is to make the download logic correct.

**Comment by TimeString** [comment]
Based on our discussion, we need to do the following changes:

- [ ] For each row in task table In the submission page, there is a detail button in the last column. Instead of disabling it when the task-grading-status is not ready, we should allow the user to click it anytime, and redirect the user to the task-grading-status page
- [ ] In the task-grading-status, show the input files in the first half (this will be blocked by #37 )
- [ ] If the task is not graded yet, hide all the output files and the grading feedback

**Comment by PARanOiA1120** [comment]
Have tested the following scenarios:
- Is able to fetch the correct zip file with the right content for each task
- Has done permission check so that 
    - users who didn't enroll the course do not have permission to download any input files even though they know the download url
   - users with only view_assignment permission cannot download input files for tasks with Feedback or Hidden mode.
