### ISSUE TITLE
Prod database conversion: Create team objects and link to previous submission records

### ISSUE THREAD

**Issue by TimeString** [nesl/AutoGrader#128]
To fill the records of teams

**Comment by TimeString** [comment]
In order to introduce the notion of team, we added tables such as "Team" and "TeamMember". However, directly migrating the database is not sufficient. We also need to create Team and TeamMember records. Otherwise, previous students cannot see their submissions anymore.

Please see the commit history for more details.

https://github.com/nesl/AutoGrader/commit/13adfe9cacb8188a190d82f88fc9e177c189c840#diff-a40273d63d312705de089f6173a385b3

Since all the previous assignments are individual assignments, a team should be defined as in assignment-student level in the previous data.

**Comment by Klamath233** [comment]
Fixed and merged.
