### ISSUE TITLE
Server Responses Should Return Correct Status Code upon Failure

### ISSUE THREAD

**Issue by Klamath233** [nesl/AutoGrader#129]
Many of the render() calls in the application are not following HTTP status code best practices. For example:
```python3
def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            activation_key = _generate_activation_key(form.cleaned_data['uid'])
            form.save_and_commit(activation_key)  # Save the user and her profile
            activation_link = request.build_absolute_uri(
                    reverse('activation', kwargs={'key': activation_key}))
            _send_activation_email(activation_link, form.cleaned_data['email'])

            request.session['registered'] = True  # For display purposes
            return render(request, 'serapis/registration_done.html', locals())
    else:
        form = UserRegistrationForm()
    return render(request, 'serapis/registration.html', {'form': form})
```

When `form.is_valid()` returns `False`, the last line of code will be executed, but with a status code of `200 OK`. It is not correct. We should have `400 Bad Request` or `403 Forbidden` in places like this.

**Comment by TimeString** [comment]
@Klamath233 , now I'm reviewing the issue: Why do you think we should return 400 instead? If the registration form is not correct, we want to ask the user to correct the registration form, so I think the current implementation is correct.
