### ISSUE TITLE
Add option to unenroll from a Course

### ISSUE THREAD

**Issue by bbalaji-ucsd** [nesl/AutoGrader#29]
Don't think I can do this now. If some student accidentally registers, we may want to remove them.

**Comment by TimeString** [comment]
Permissions should be removed after the unenrollment. Please address all the comments before closing this issue: https://github.com/nesl/AutoGrader/commit/5e5570925e031538a1872839cde17c40f922ae0a

**Comment by TimeString** [comment]
Didn't see one commit, all the issues are addressed. Thanks @PARanOiA1120 !
