### ISSUE TITLE
Verify registration form in place rather than wait to submit

### ISSUE THREAD

**Issue by bbalaji-ucsd** [nesl/AutoGrader#44]
If the password field doesn't match, the user is only notified after they submit. And, the entire form gets erased.

**Comment by TimeString** [comment]
I've fixed the issue that the form got erased when a user clicks submit button but errors occur. I don't think there's built-in thing in django which verifies two password fields are identical without making a new request.

**Comment by Klamath233** [comment]
Added a password check in the front end.
