### ISSUE TITLE
Delete task button does not work

### ISSUE THREAD

**Issue by bbalaji-ucsd** [nesl/AutoGrader#48]
Goes to the assignment page without deleting the task

**Comment by Klamath233** [comment]
@TimeString Is this problem still there?

**Comment by TimeString** [comment]
It's over everywhere (I think) haha

- [ ] Delete course
- [ ] Delete assignment
- [ ] Delete task

**Comment by TimeString** [comment]
@Klamath233 suggests that HTTP GET shouldn't change the server side states. We have to go over this issue again.

- [ ] Delete course
- [ ] Delete assignment
- [ ] Delete task

**Comment by TimeString** [comment]
@Klamath233: I think part of the reason that we want to stay with HTTP POST is that we can check csrf_token. The easiest way to do it is wrapping the token in the form. But basically all the forms for deletion would be empty. Should we create a generic deletion form?

**Comment by Klamath233** [comment]
I need to think a little bit.

**Comment by TimeString** [comment]
So the conclusion is that we use javascript to issue the POST request, and in the view function we need to check if this is a HTTP POST request

**Comment by TimeString** [comment]
We can follow this example for removing object tasks:
https://djangosnippets.org/snippets/10548/
